//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.PowerOnRent {
    
    
    public partial class TestFilter {
        
        /// <summary>
        /// UCCommonFilter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::WebClientElegantCRM.PowerOnRent.UCCommonFilter UCCommonFilter1;
        protected global::PowerOnRentwebapp.PowerOnRent.UCCommonFilter UCCommonFilter1;
    }
}

