//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.ApprovalLevelMasterService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApprovalLevelMasterService.iApprovalLevelMaster")]
    public interface iApprovalLevelMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetActivityList", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetActivityListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel[] GetActivityList(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/InsertmApprovalLevel", ReplyAction="http://tempuri.org/iApprovalLevelMaster/InsertmApprovalLevelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int InsertmApprovalLevel(PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel approval, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/updatemApprovalLevel", ReplyAction="http://tempuri.org/iApprovalLevelMaster/updatemApprovalLevelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int updatemApprovalLevel(PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel updateApproval, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetApprovalRecordByID", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetApprovalRecordByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel GetApprovalRecordByID(int approvalId, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetApprovalDetailRecordByID", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetApprovalDetailRecordByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevelDetail[] GetApprovalDetailRecordByID(int approvalDetailId, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetObjectList", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetObjectListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.sysmObject[] GetObjectList(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetApprovalLevelMax", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetApprovalLevelMaxResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int GetApprovalLevelMax(string objName, long TerritoryID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetApprovalRecordToBindGrid", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetApprovalRecordToBindGridResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetApprovalRecordToBindGrid(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetUserListForEdit", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetUserListForEditResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevelDetail[] GetUserListForEdit(int approvalid, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetUserListForEditbySP", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetUserListForEditbySPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.SP_GetUserForApprovalMaster_Result[] GetUserListForEditbySP(int approvalid, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/SaveApprovalLevelDetail", ReplyAction="http://tempuri.org/iApprovalLevelMaster/SaveApprovalLevelDetailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool SaveApprovalLevelDetail(string paraUserIDs, long paraApprovalLevelID, PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevelDetail paraInput, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iApprovalLevelMaster/GetUserListForEditbySPResult", ReplyAction="http://tempuri.org/iApprovalLevelMaster/GetUserListForEditbySPResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(mApprovalLevel[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ApprovalLevelMasterService.SP_GetUserForApprovalMaster_Result[] GetUserListForEditbySPResult(int approvalid, string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mApprovalLevel : EntityObject {
        
        private long idField;
        
        private string objectNameField;
        
        private byte approvalLevelField;
        
        private byte noOfApproversField;
        
        private byte minApprovalReqField;
        
        private bool isLowerLevelApprovalReqField;
        
        private decimal maxAmountField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private System.Nullable<long> territoryIDField;
        
        private EntityReferenceOfsysmObject sysmObjectReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public byte ApprovalLevel {
            get {
                return this.approvalLevelField;
            }
            set {
                this.approvalLevelField = value;
                this.RaisePropertyChanged("ApprovalLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public byte NoOfApprovers {
            get {
                return this.noOfApproversField;
            }
            set {
                this.noOfApproversField = value;
                this.RaisePropertyChanged("NoOfApprovers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public byte MinApprovalReq {
            get {
                return this.minApprovalReqField;
            }
            set {
                this.minApprovalReqField = value;
                this.RaisePropertyChanged("MinApprovalReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsLowerLevelApprovalReq {
            get {
                return this.isLowerLevelApprovalReqField;
            }
            set {
                this.isLowerLevelApprovalReqField = value;
                this.RaisePropertyChanged("IsLowerLevelApprovalReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal MaxAmount {
            get {
                return this.maxAmountField;
            }
            set {
                this.maxAmountField = value;
                this.RaisePropertyChanged("MaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> TerritoryID {
            get {
                return this.territoryIDField;
            }
            set {
                this.territoryIDField = value;
                this.RaisePropertyChanged("TerritoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public EntityReferenceOfsysmObject sysmObjectReference {
            get {
                return this.sysmObjectReferenceField;
            }
            set {
                this.sysmObjectReferenceField = value;
                this.RaisePropertyChanged("sysmObjectReference");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfsysmObject : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfsysmObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfsysmObject))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SP_GetUserForApprovalMaster_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sysmObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mApprovalLevelDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mApprovalLevel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SP_GetUserForApprovalMaster_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ComplexObject : StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_GetUserForApprovalMaster_Result : ComplexObject {
        
        private string checkedField;
        
        private string nameField;
        
        private long idField;
        
        private string employeeIDField;
        
        private string activeField;
        
        private long departmentIDField;
        
        private string deptNameField;
        
        private long designationIDField;
        
        private string desiNameField;
        
        private string emailIDField;
        
        private string mobileNoField;
        
        private string phoneNoField;
        
        private System.Nullable<long> roleIDField;
        
        private string roleNameField;
        
        private string selectedRecField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @checked {
            get {
                return this.checkedField;
            }
            set {
                this.checkedField = value;
                this.RaisePropertyChanged("checked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long DepartmentID {
            get {
                return this.departmentIDField;
            }
            set {
                this.departmentIDField = value;
                this.RaisePropertyChanged("DepartmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DeptName {
            get {
                return this.deptNameField;
            }
            set {
                this.deptNameField = value;
                this.RaisePropertyChanged("DeptName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long DesignationID {
            get {
                return this.designationIDField;
            }
            set {
                this.designationIDField = value;
                this.RaisePropertyChanged("DesignationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DesiName {
            get {
                return this.desiNameField;
            }
            set {
                this.desiNameField = value;
                this.RaisePropertyChanged("DesiName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EmailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
                this.RaisePropertyChanged("EmailID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
                this.RaisePropertyChanged("MobileNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<long> RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
                this.RaisePropertyChanged("RoleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("RoleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string SelectedRec {
            get {
                return this.selectedRecField;
            }
            set {
                this.selectedRecField = value;
                this.RaisePropertyChanged("SelectedRec");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sysmObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mApprovalLevelDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mApprovalLevel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class sysmObject : EntityObject {
        
        private string phaseNameField;
        
        private string objectNameField;
        
        private string objectDisplayNameField;
        
        private bool approvalProcessField;
        
        private bool assignTaskProcessField;
        
        private long sequenceField;
        
        private string headerMenuField;
        
        private string formUrlField;
        
        private string createdByField;
        
        private System.DateTime createdDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private EntityReferenceOfsysmObject sysmObjects1ReferenceField;
        
        private EntityReferenceOfsysmObject sysmObject1ReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhaseName {
            get {
                return this.phaseNameField;
            }
            set {
                this.phaseNameField = value;
                this.RaisePropertyChanged("PhaseName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ObjectDisplayName {
            get {
                return this.objectDisplayNameField;
            }
            set {
                this.objectDisplayNameField = value;
                this.RaisePropertyChanged("ObjectDisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ApprovalProcess {
            get {
                return this.approvalProcessField;
            }
            set {
                this.approvalProcessField = value;
                this.RaisePropertyChanged("ApprovalProcess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool AssignTaskProcess {
            get {
                return this.assignTaskProcessField;
            }
            set {
                this.assignTaskProcessField = value;
                this.RaisePropertyChanged("AssignTaskProcess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string HeaderMenu {
            get {
                return this.headerMenuField;
            }
            set {
                this.headerMenuField = value;
                this.RaisePropertyChanged("HeaderMenu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FormUrl {
            get {
                return this.formUrlField;
            }
            set {
                this.formUrlField = value;
                this.RaisePropertyChanged("FormUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public EntityReferenceOfsysmObject sysmObjects1Reference {
            get {
                return this.sysmObjects1ReferenceField;
            }
            set {
                this.sysmObjects1ReferenceField = value;
                this.RaisePropertyChanged("sysmObjects1Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public EntityReferenceOfsysmObject sysmObject1Reference {
            get {
                return this.sysmObject1ReferenceField;
            }
            set {
                this.sysmObject1ReferenceField = value;
                this.RaisePropertyChanged("sysmObject1Reference");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mApprovalLevelDetail : EntityObject {
        
        private long idField;
        
        private long approvalLevelIDField;
        
        private long userIDField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private long companyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ApprovalLevelID {
            get {
                return this.approvalLevelIDField;
            }
            set {
                this.approvalLevelIDField = value;
                this.RaisePropertyChanged("ApprovalLevelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iApprovalLevelMasterChannel : PowerOnRentwebapp.ApprovalLevelMasterService.iApprovalLevelMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iApprovalLevelMasterClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.ApprovalLevelMasterService.iApprovalLevelMaster>, PowerOnRentwebapp.ApprovalLevelMasterService.iApprovalLevelMaster {
        
        public iApprovalLevelMasterClient() {
        }
        
        public iApprovalLevelMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iApprovalLevelMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iApprovalLevelMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iApprovalLevelMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel[] GetActivityList(string[] conn) {
            return base.Channel.GetActivityList(conn);
        }
        
        public int InsertmApprovalLevel(PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel approval, string[] conn) {
            return base.Channel.InsertmApprovalLevel(approval, conn);
        }
        
        public int updatemApprovalLevel(PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel updateApproval, string[] conn) {
            return base.Channel.updatemApprovalLevel(updateApproval, conn);
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevel GetApprovalRecordByID(int approvalId, string[] conn) {
            return base.Channel.GetApprovalRecordByID(approvalId, conn);
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevelDetail[] GetApprovalDetailRecordByID(int approvalDetailId, string[] conn) {
            return base.Channel.GetApprovalDetailRecordByID(approvalDetailId, conn);
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.sysmObject[] GetObjectList(string[] conn) {
            return base.Channel.GetObjectList(conn);
        }
        
        public int GetApprovalLevelMax(string objName, long TerritoryID, string[] conn) {
            return base.Channel.GetApprovalLevelMax(objName, TerritoryID, conn);
        }
        
        public System.Data.DataSet GetApprovalRecordToBindGrid(string[] conn) {
            return base.Channel.GetApprovalRecordToBindGrid(conn);
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevelDetail[] GetUserListForEdit(int approvalid, string[] conn) {
            return base.Channel.GetUserListForEdit(approvalid, conn);
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.SP_GetUserForApprovalMaster_Result[] GetUserListForEditbySP(int approvalid, string[] conn) {
            return base.Channel.GetUserListForEditbySP(approvalid, conn);
        }
        
        public bool SaveApprovalLevelDetail(string paraUserIDs, long paraApprovalLevelID, PowerOnRentwebapp.ApprovalLevelMasterService.mApprovalLevelDetail paraInput, string[] conn) {
            return base.Channel.SaveApprovalLevelDetail(paraUserIDs, paraApprovalLevelID, paraInput, conn);
        }
        
        public PowerOnRentwebapp.ApprovalLevelMasterService.SP_GetUserForApprovalMaster_Result[] GetUserListForEditbySPResult(int approvalid, string[] conn) {
            return base.Channel.GetUserListForEditbySPResult(approvalid, conn);
        }
    }
}
