//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.PORServicePartRequest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PORServicePartRequest.iPartRequest")]
    public interface iPartRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetRequestHeadByRequestID", ReplyAction="http://tempuri.org/iPartRequest/GetRequestHeadByRequestIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.PORtPartRequestHead GetRequestHeadByRequestID(long RequestID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/SetIntoPartRequestHead", ReplyAction="http://tempuri.org/iPartRequest/SetIntoPartRequestHeadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long SetIntoPartRequestHead(PowerOnRentwebapp.PORServicePartRequest.PORtPartRequestHead PartRequest, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetStatusListForRequest", ReplyAction="http://tempuri.org/iPartRequest/GetStatusListForRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.mStatu[] GetStatusListForRequest(string Remark, string state, long UserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetRequestPartDetailByRequestID", ReplyAction="http://tempuri.org/iPartRequest/GetRequestPartDetailByRequestIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] GetRequestPartDetailByRequestID(long RequestID, long siteID, string sessionID, string userID, string CurrentObject, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/ClearTempDataFromDB", ReplyAction="http://tempuri.org/iPartRequest/ClearTempDataFromDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void ClearTempDataFromDB(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetExistingTempDataBySessionIDObjectName", ReplyAction="http://tempuri.org/iPartRequest/GetExistingTempDataBySessionIDObjectNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] GetExistingTempDataBySessionIDObjectName(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/AddPartIntoRequest_TempData", ReplyAction="http://tempuri.org/iPartRequest/AddPartIntoRequest_TempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] AddPartIntoRequest_TempData(string paraProductIDs, string paraSessionID, string paraUserID, string paraCurrentObjectName, long SiteID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/RemovePartFromRequest_TempData", ReplyAction="http://tempuri.org/iPartRequest/RemovePartFromRequest_TempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] RemovePartFromRequest_TempData(string paraSessionID, string paraUserID, string paraCurrentObjectName, int paraSequence, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/UpdatePartRequest_TempData", ReplyAction="http://tempuri.org/iPartRequest/UpdatePartRequest_TempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdatePartRequest_TempData(string SessionID, string CurrentObjectName, string UserID, PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result Request, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/FinalSaveRequestPartDetail", ReplyAction="http://tempuri.org/iPartRequest/FinalSaveRequestPartDetailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void FinalSaveRequestPartDetail(string paraSessionID, string paraCurrentObjectName, long paraReferenceID, string paraUserID, int StatusID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetRequestSummayByUserID", ReplyAction="http://tempuri.org/iPartRequest/GetRequestSummayByUserIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetRequestBySiteIDsOrUserID_Result[] GetRequestSummayByUserID(long UserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetRequestSummayBySiteIDs", ReplyAction="http://tempuri.org/iPartRequest/GetRequestSummayBySiteIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetRequestBySiteIDsOrUserID_Result[] GetRequestSummayBySiteIDs(string SiteIDs, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetRequestSummayByRequestIDs", ReplyAction="http://tempuri.org/iPartRequest/GetRequestSummayByRequestIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetRequestByRequestIDs_Result[] GetRequestSummayByRequestIDs(string RequestIDs, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/SaveApprovalStatus", ReplyAction="http://tempuri.org/iPartRequest/SaveApprovalStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string SaveApprovalStatus(long RequestID, string ApprovalStatus, string ApprovalRemark, long UserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartRequest/GetApprovalDetailsByReqestID", ReplyAction="http://tempuri.org/iPartRequest/GetApprovalDetailsByReqestIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartRequest.tApprovalDetail GetApprovalDetailsByReqestID(long RequestID, string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PORtPartRequestHead : EntityObject {
        
        private long pRH_IDField;
        
        private System.Nullable<long> siteIDField;
        
        private string requestNoField;
        
        private string requestTypeField;
        
        private System.Nullable<long> statusIDField;
        
        private string titleField;
        
        private System.Nullable<System.DateTime> requestDateField;
        
        private System.Nullable<long> requestByField;
        
        private string remarkField;
        
        private string failureCauseField;
        
        private string failureHoursField;
        
        private string failureNatureField;
        
        private string engineSerialField;
        
        private string engineModelField;
        
        private string generatorModelField;
        
        private string generatorSerialField;
        
        private string transformerSerialField;
        
        private string containerField;
        
        private System.Nullable<System.DateTime> probableShippingDateField;
        
        private System.Nullable<bool> isSubmitField;
        
        private System.Nullable<long> createdByField;
        
        private System.Nullable<System.DateTime> creationDtField;
        
        private System.Nullable<long> lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDtField;
        
        private EntityReferenceOfmStatu mStatuReferenceField;
        
        private EntityReferenceOfmTerritory mTerritoryReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long PRH_ID {
            get {
                return this.pRH_IDField;
            }
            set {
                this.pRH_IDField = value;
                this.RaisePropertyChanged("PRH_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestNo {
            get {
                return this.requestNoField;
            }
            set {
                this.requestNoField = value;
                this.RaisePropertyChanged("RequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
                this.RaisePropertyChanged("StatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> RequestBy {
            get {
                return this.requestByField;
            }
            set {
                this.requestByField = value;
                this.RaisePropertyChanged("RequestBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FailureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
                this.RaisePropertyChanged("FailureCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FailureHours {
            get {
                return this.failureHoursField;
            }
            set {
                this.failureHoursField = value;
                this.RaisePropertyChanged("FailureHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FailureNature {
            get {
                return this.failureNatureField;
            }
            set {
                this.failureNatureField = value;
                this.RaisePropertyChanged("FailureNature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string EngineSerial {
            get {
                return this.engineSerialField;
            }
            set {
                this.engineSerialField = value;
                this.RaisePropertyChanged("EngineSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string EngineModel {
            get {
                return this.engineModelField;
            }
            set {
                this.engineModelField = value;
                this.RaisePropertyChanged("EngineModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GeneratorModel {
            get {
                return this.generatorModelField;
            }
            set {
                this.generatorModelField = value;
                this.RaisePropertyChanged("GeneratorModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string GeneratorSerial {
            get {
                return this.generatorSerialField;
            }
            set {
                this.generatorSerialField = value;
                this.RaisePropertyChanged("GeneratorSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TransformerSerial {
            get {
                return this.transformerSerialField;
            }
            set {
                this.transformerSerialField = value;
                this.RaisePropertyChanged("TransformerSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
                this.RaisePropertyChanged("Container");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> ProbableShippingDate {
            get {
                return this.probableShippingDateField;
            }
            set {
                this.probableShippingDateField = value;
                this.RaisePropertyChanged("ProbableShippingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<bool> IsSubmit {
            get {
                return this.isSubmitField;
            }
            set {
                this.isSubmitField = value;
                this.RaisePropertyChanged("IsSubmit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<long> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> CreationDt {
            get {
                return this.creationDtField;
            }
            set {
                this.creationDtField = value;
                this.RaisePropertyChanged("CreationDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<long> LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> LastModifiedDt {
            get {
                return this.lastModifiedDtField;
            }
            set {
                this.lastModifiedDtField = value;
                this.RaisePropertyChanged("LastModifiedDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public EntityReferenceOfmStatu mStatuReference {
            get {
                return this.mStatuReferenceField;
            }
            set {
                this.mStatuReferenceField = value;
                this.RaisePropertyChanged("mStatuReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public EntityReferenceOfmTerritory mTerritoryReference {
            get {
                return this.mTerritoryReferenceField;
            }
            set {
                this.mTerritoryReferenceField = value;
                this.RaisePropertyChanged("mTerritoryReference");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfmStatu : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfmTerritory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfmStatu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfmTerritory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfmStatu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetRequestByRequestIDs_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetRequestBySiteIDsOrUserID_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetPartDetail_ForRequest_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tApprovalDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PORtPartRequestHead))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mStatu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetRequestByRequestIDs_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetRequestBySiteIDsOrUserID_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetPartDetail_ForRequest_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ComplexObject : StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class POR_SP_GetRequestByRequestIDs_Result : ComplexObject {
        
        private long pRH_IDField;
        
        private string siteNameField;
        
        private long siteIDField;
        
        private string requestNoField;
        
        private System.Nullable<System.DateTime> requestDateField;
        
        private string titleField;
        
        private string requestTypeField;
        
        private System.Nullable<long> requestByField;
        
        private string requestByUserNameField;
        
        private System.Nullable<long> statusIDField;
        
        private string requestStatusField;
        
        private string imgRequestField;
        
        private string imgApprovalField;
        
        private string imgIssueField;
        
        private string imgReceiptField;
        
        private string imgConsumptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long PRH_ID {
            get {
                return this.pRH_IDField;
            }
            set {
                this.pRH_IDField = value;
                this.RaisePropertyChanged("PRH_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestNo {
            get {
                return this.requestNoField;
            }
            set {
                this.requestNoField = value;
                this.RaisePropertyChanged("RequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> RequestBy {
            get {
                return this.requestByField;
            }
            set {
                this.requestByField = value;
                this.RaisePropertyChanged("RequestBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RequestByUserName {
            get {
                return this.requestByUserNameField;
            }
            set {
                this.requestByUserNameField = value;
                this.RaisePropertyChanged("RequestByUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
                this.RaisePropertyChanged("StatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RequestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
                this.RaisePropertyChanged("RequestStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ImgRequest {
            get {
                return this.imgRequestField;
            }
            set {
                this.imgRequestField = value;
                this.RaisePropertyChanged("ImgRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ImgApproval {
            get {
                return this.imgApprovalField;
            }
            set {
                this.imgApprovalField = value;
                this.RaisePropertyChanged("ImgApproval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ImgIssue {
            get {
                return this.imgIssueField;
            }
            set {
                this.imgIssueField = value;
                this.RaisePropertyChanged("ImgIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ImgReceipt {
            get {
                return this.imgReceiptField;
            }
            set {
                this.imgReceiptField = value;
                this.RaisePropertyChanged("ImgReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ImgConsumption {
            get {
                return this.imgConsumptionField;
            }
            set {
                this.imgConsumptionField = value;
                this.RaisePropertyChanged("ImgConsumption");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class POR_SP_GetRequestBySiteIDsOrUserID_Result : ComplexObject {
        
        private long pRH_IDField;
        
        private string siteNameField;
        
        private long siteIDField;
        
        private string requestNoField;
        
        private System.Nullable<System.DateTime> requestDateField;
        
        private string titleField;
        
        private string requestTypeField;
        
        private System.Nullable<long> requestByField;
        
        private string requestByUserNameField;
        
        private System.Nullable<long> statusIDField;
        
        private string requestStatusField;
        
        private string imgRequestField;
        
        private string imgApprovalField;
        
        private string imgIssueField;
        
        private string imgReceiptField;
        
        private string imgConsumptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long PRH_ID {
            get {
                return this.pRH_IDField;
            }
            set {
                this.pRH_IDField = value;
                this.RaisePropertyChanged("PRH_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RequestNo {
            get {
                return this.requestNoField;
            }
            set {
                this.requestNoField = value;
                this.RaisePropertyChanged("RequestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> RequestBy {
            get {
                return this.requestByField;
            }
            set {
                this.requestByField = value;
                this.RaisePropertyChanged("RequestBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RequestByUserName {
            get {
                return this.requestByUserNameField;
            }
            set {
                this.requestByUserNameField = value;
                this.RaisePropertyChanged("RequestByUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<long> StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
                this.RaisePropertyChanged("StatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string RequestStatus {
            get {
                return this.requestStatusField;
            }
            set {
                this.requestStatusField = value;
                this.RaisePropertyChanged("RequestStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ImgRequest {
            get {
                return this.imgRequestField;
            }
            set {
                this.imgRequestField = value;
                this.RaisePropertyChanged("ImgRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ImgApproval {
            get {
                return this.imgApprovalField;
            }
            set {
                this.imgApprovalField = value;
                this.RaisePropertyChanged("ImgApproval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ImgIssue {
            get {
                return this.imgIssueField;
            }
            set {
                this.imgIssueField = value;
                this.RaisePropertyChanged("ImgIssue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ImgReceipt {
            get {
                return this.imgReceiptField;
            }
            set {
                this.imgReceiptField = value;
                this.RaisePropertyChanged("ImgReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ImgConsumption {
            get {
                return this.imgConsumptionField;
            }
            set {
                this.imgConsumptionField = value;
                this.RaisePropertyChanged("ImgConsumption");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class POR_SP_GetPartDetail_ForRequest_Result : ComplexObject {
        
        private string pRD_IDField;
        
        private string pRH_IDField;
        
        private long prod_IDField;
        
        private string prod_CodeField;
        
        private string prod_NameField;
        
        private string prod_DescriptionField;
        
        private string uOMField;
        
        private long uOMIDField;
        
        private decimal requestQtyField;
        
        private decimal remaningQtyField;
        
        private System.Nullable<long> sequenceField;
        
        private System.Nullable<decimal> currentStockField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PRD_ID {
            get {
                return this.pRD_IDField;
            }
            set {
                this.pRD_IDField = value;
                this.RaisePropertyChanged("PRD_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PRH_ID {
            get {
                return this.pRH_IDField;
            }
            set {
                this.pRH_IDField = value;
                this.RaisePropertyChanged("PRH_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Prod_ID {
            get {
                return this.prod_IDField;
            }
            set {
                this.prod_IDField = value;
                this.RaisePropertyChanged("Prod_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Prod_Code {
            get {
                return this.prod_CodeField;
            }
            set {
                this.prod_CodeField = value;
                this.RaisePropertyChanged("Prod_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Prod_Name {
            get {
                return this.prod_NameField;
            }
            set {
                this.prod_NameField = value;
                this.RaisePropertyChanged("Prod_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Prod_Description {
            get {
                return this.prod_DescriptionField;
            }
            set {
                this.prod_DescriptionField = value;
                this.RaisePropertyChanged("Prod_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long UOMID {
            get {
                return this.uOMIDField;
            }
            set {
                this.uOMIDField = value;
                this.RaisePropertyChanged("UOMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal RequestQty {
            get {
                return this.requestQtyField;
            }
            set {
                this.requestQtyField = value;
                this.RaisePropertyChanged("RequestQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal RemaningQty {
            get {
                return this.remaningQtyField;
            }
            set {
                this.remaningQtyField = value;
                this.RaisePropertyChanged("RemaningQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> CurrentStock {
            get {
                return this.currentStockField;
            }
            set {
                this.currentStockField = value;
                this.RaisePropertyChanged("CurrentStock");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tApprovalDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PORtPartRequestHead))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mStatu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tApprovalDetail : EntityObject {
        
        private long idField;
        
        private string objectNameField;
        
        private System.Nullable<long> referenceIDField;
        
        private System.Nullable<byte> approvalLevelField;
        
        private System.Nullable<bool> isRequiredField;
        
        private System.Nullable<bool> mailAlertField;
        
        private string statusField;
        
        private System.Nullable<long> approverUserIDField;
        
        private System.Nullable<long> statusChangedByField;
        
        private System.Nullable<System.DateTime> approvedDateField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private System.Nullable<decimal> objectTotalAmountField;
        
        private string remarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<byte> ApprovalLevel {
            get {
                return this.approvalLevelField;
            }
            set {
                this.approvalLevelField = value;
                this.RaisePropertyChanged("ApprovalLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> IsRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
                this.RaisePropertyChanged("IsRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> MailAlert {
            get {
                return this.mailAlertField;
            }
            set {
                this.mailAlertField = value;
                this.RaisePropertyChanged("MailAlert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> ApproverUserID {
            get {
                return this.approverUserIDField;
            }
            set {
                this.approverUserIDField = value;
                this.RaisePropertyChanged("ApproverUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<long> StatusChangedBy {
            get {
                return this.statusChangedByField;
            }
            set {
                this.statusChangedByField = value;
                this.RaisePropertyChanged("StatusChangedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> ApprovedDate {
            get {
                return this.approvedDateField;
            }
            set {
                this.approvedDateField = value;
                this.RaisePropertyChanged("ApprovedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> ObjectTotalAmount {
            get {
                return this.objectTotalAmountField;
            }
            set {
                this.objectTotalAmountField = value;
                this.RaisePropertyChanged("ObjectTotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mStatu : EntityObject {
        
        private long idField;
        
        private string objectNameField;
        
        private System.Nullable<long> sequenceField;
        
        private string statusField;
        
        private string remarkField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private long companyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfmTerritory : EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iPartRequestChannel : PowerOnRentwebapp.PORServicePartRequest.iPartRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iPartRequestClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.PORServicePartRequest.iPartRequest>, PowerOnRentwebapp.PORServicePartRequest.iPartRequest {
        
        public iPartRequestClient() {
        }
        
        public iPartRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iPartRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPartRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPartRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.PORtPartRequestHead GetRequestHeadByRequestID(long RequestID, string[] conn) {
            return base.Channel.GetRequestHeadByRequestID(RequestID, conn);
        }
        
        public long SetIntoPartRequestHead(PowerOnRentwebapp.PORServicePartRequest.PORtPartRequestHead PartRequest, string[] conn) {
            return base.Channel.SetIntoPartRequestHead(PartRequest, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.mStatu[] GetStatusListForRequest(string Remark, string state, long UserID, string[] conn) {
            return base.Channel.GetStatusListForRequest(Remark, state, UserID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] GetRequestPartDetailByRequestID(long RequestID, long siteID, string sessionID, string userID, string CurrentObject, string[] conn) {
            return base.Channel.GetRequestPartDetailByRequestID(RequestID, siteID, sessionID, userID, CurrentObject, conn);
        }
        
        public void ClearTempDataFromDB(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn) {
            base.Channel.ClearTempDataFromDB(paraSessionID, paraUserID, paraCurrentObjectName, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] GetExistingTempDataBySessionIDObjectName(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn) {
            return base.Channel.GetExistingTempDataBySessionIDObjectName(paraSessionID, paraUserID, paraCurrentObjectName, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] AddPartIntoRequest_TempData(string paraProductIDs, string paraSessionID, string paraUserID, string paraCurrentObjectName, long SiteID, string[] conn) {
            return base.Channel.AddPartIntoRequest_TempData(paraProductIDs, paraSessionID, paraUserID, paraCurrentObjectName, SiteID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result[] RemovePartFromRequest_TempData(string paraSessionID, string paraUserID, string paraCurrentObjectName, int paraSequence, string[] conn) {
            return base.Channel.RemovePartFromRequest_TempData(paraSessionID, paraUserID, paraCurrentObjectName, paraSequence, conn);
        }
        
        public void UpdatePartRequest_TempData(string SessionID, string CurrentObjectName, string UserID, PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetPartDetail_ForRequest_Result Request, string[] conn) {
            base.Channel.UpdatePartRequest_TempData(SessionID, CurrentObjectName, UserID, Request, conn);
        }
        
        public void FinalSaveRequestPartDetail(string paraSessionID, string paraCurrentObjectName, long paraReferenceID, string paraUserID, int StatusID, string[] conn) {
            base.Channel.FinalSaveRequestPartDetail(paraSessionID, paraCurrentObjectName, paraReferenceID, paraUserID, StatusID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetRequestBySiteIDsOrUserID_Result[] GetRequestSummayByUserID(long UserID, string[] conn) {
            return base.Channel.GetRequestSummayByUserID(UserID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetRequestBySiteIDsOrUserID_Result[] GetRequestSummayBySiteIDs(string SiteIDs, string[] conn) {
            return base.Channel.GetRequestSummayBySiteIDs(SiteIDs, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.POR_SP_GetRequestByRequestIDs_Result[] GetRequestSummayByRequestIDs(string RequestIDs, string[] conn) {
            return base.Channel.GetRequestSummayByRequestIDs(RequestIDs, conn);
        }
        
        public string SaveApprovalStatus(long RequestID, string ApprovalStatus, string ApprovalRemark, long UserID, string[] conn) {
            return base.Channel.SaveApprovalStatus(RequestID, ApprovalStatus, ApprovalRemark, UserID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartRequest.tApprovalDetail GetApprovalDetailsByReqestID(long RequestID, string[] conn) {
            return base.Channel.GetApprovalDetailsByReqestID(RequestID, conn);
        }
    }
}
