//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.PORServicePartConsumption {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PORServicePartConsumption.iPartConsumption")]
    public interface iPartConsumption {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionHeadByConsumptionID", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionHeadByConsumptionIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.PORtConsumptionHead GetConsumptionHeadByConsumptionID(long ConsumptionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/SetIntoPartConsumptionHead", ReplyAction="http://tempuri.org/iPartConsumption/SetIntoPartConsumptionHeadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        long SetIntoPartConsumptionHead(PowerOnRentwebapp.PORServicePartConsumption.PORtConsumptionHead ConsumptionHead, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetStatusListForConsumption", ReplyAction="http://tempuri.org/iPartConsumption/GetStatusListForConsumptionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.mStatu[] GetStatusListForConsumption(string Remark, string state, long UserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionPartDetailByReceiptID", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionPartDetailByReceiptIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] GetConsumptionPartDetailByReceiptID(long ReceiptID, long siteID, string sessionID, string userID, string CurrentObject, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionPartDetailByConsumptionID", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionPartDetailByConsumptionIDRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] GetConsumptionPartDetailByConsumptionID(long ConsumptionID, long siteID, string sessionID, string userID, string CurrentObject, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/ClearTempDataFromDB", ReplyAction="http://tempuri.org/iPartConsumption/ClearTempDataFromDBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void ClearTempDataFromDB(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetExistingTempDataBySessionIDObjectName", ReplyAction="http://tempuri.org/iPartConsumption/GetExistingTempDataBySessionIDObjectNameRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] GetExistingTempDataBySessionIDObjectName(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/AddPartIntoConsumption_TempDataByPartIDs", ReplyAction="http://tempuri.org/iPartConsumption/AddPartIntoConsumption_TempDataByPartIDsRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] AddPartIntoConsumption_TempDataByPartIDs(string paraProductIDs, string paraSessionID, string paraUserID, string paraCurrentObjectName, long SiteID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/AddPartIntoConsumption_TempDataByGrdIDs", ReplyAction="http://tempuri.org/iPartConsumption/AddPartIntoConsumption_TempDataByGrdIDsRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] AddPartIntoConsumption_TempDataByGrdIDs(string GrdIDs, string paraSessionID, string paraUserID, string paraCurrentObjectName, long SiteID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/RemovePartFrom_TempData", ReplyAction="http://tempuri.org/iPartConsumption/RemovePartFrom_TempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] RemovePartFrom_TempData(string paraSessionID, string paraUserID, string paraCurrentObjectName, int paraSequence, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/UpdatePartConsumedQty_TempData", ReplyAction="http://tempuri.org/iPartConsumption/UpdatePartConsumedQty_TempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void UpdatePartConsumedQty_TempData(string SessionID, string CurrentObjectName, string UserID, PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result Consumption, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/FinalSavePartDetail", ReplyAction="http://tempuri.org/iPartConsumption/FinalSavePartDetailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        void FinalSavePartDetail(string paraSessionID, string paraCurrentObjectName, long paraReferenceID, string paraUserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionSummayByUserID", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionSummayByUserIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayByUserID(long UserID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionSummayBySiteIDs", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionSummayBySiteIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayBySiteIDs(string SiteIDs, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionSummayByReceiptIDs", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionSummayByReceiptIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayByReceiptIDs(string ReceiptIDs, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iPartConsumption/GetConsumptionSummayByConsumptionIDs", ReplyAction="http://tempuri.org/iPartConsumption/GetConsumptionSummayByConsumptionIDsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayByConsumptionIDs(string ConsumptionIDs, string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PORtConsumptionHead : EntityObject {
        
        private long conH_IDField;
        
        private System.Nullable<long> siteIDField;
        
        private System.Nullable<System.DateTime> consumptionDateField;
        
        private string objectNameField;
        
        private System.Nullable<long> referenceIDField;
        
        private System.Nullable<long> consumedByUserIDField;
        
        private string titleField;
        
        private string failureCauseField;
        
        private string failureHoursField;
        
        private string failureNatureField;
        
        private string engineSerialField;
        
        private string engineModelField;
        
        private string generatorModelField;
        
        private string generatorSerialField;
        
        private string transformerSerialField;
        
        private string containerField;
        
        private string remarkField;
        
        private System.Nullable<long> createdByField;
        
        private System.Nullable<System.DateTime> creationDtField;
        
        private System.Nullable<long> lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDtField;
        
        private System.Nullable<long> statusIDField;
        
        private EntityReferenceOfmTerritory mTerritoryReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ConH_ID {
            get {
                return this.conH_IDField;
            }
            set {
                this.conH_IDField = value;
                this.RaisePropertyChanged("ConH_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ConsumptionDate {
            get {
                return this.consumptionDateField;
            }
            set {
                this.consumptionDateField = value;
                this.RaisePropertyChanged("ConsumptionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> ConsumedByUserID {
            get {
                return this.consumedByUserIDField;
            }
            set {
                this.consumedByUserIDField = value;
                this.RaisePropertyChanged("ConsumedByUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FailureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
                this.RaisePropertyChanged("FailureCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FailureHours {
            get {
                return this.failureHoursField;
            }
            set {
                this.failureHoursField = value;
                this.RaisePropertyChanged("FailureHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FailureNature {
            get {
                return this.failureNatureField;
            }
            set {
                this.failureNatureField = value;
                this.RaisePropertyChanged("FailureNature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string EngineSerial {
            get {
                return this.engineSerialField;
            }
            set {
                this.engineSerialField = value;
                this.RaisePropertyChanged("EngineSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string EngineModel {
            get {
                return this.engineModelField;
            }
            set {
                this.engineModelField = value;
                this.RaisePropertyChanged("EngineModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string GeneratorModel {
            get {
                return this.generatorModelField;
            }
            set {
                this.generatorModelField = value;
                this.RaisePropertyChanged("GeneratorModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string GeneratorSerial {
            get {
                return this.generatorSerialField;
            }
            set {
                this.generatorSerialField = value;
                this.RaisePropertyChanged("GeneratorSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TransformerSerial {
            get {
                return this.transformerSerialField;
            }
            set {
                this.transformerSerialField = value;
                this.RaisePropertyChanged("TransformerSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
                this.RaisePropertyChanged("Container");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<long> CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> CreationDt {
            get {
                return this.creationDtField;
            }
            set {
                this.creationDtField = value;
                this.RaisePropertyChanged("CreationDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<long> LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> LastModifiedDt {
            get {
                return this.lastModifiedDtField;
            }
            set {
                this.lastModifiedDtField = value;
                this.RaisePropertyChanged("LastModifiedDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<long> StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
                this.RaisePropertyChanged("StatusID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public EntityReferenceOfmTerritory mTerritoryReference {
            get {
                return this.mTerritoryReferenceField;
            }
            set {
                this.mTerritoryReferenceField = value;
                this.RaisePropertyChanged("mTerritoryReference");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfmTerritory : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfmTerritory))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfmTerritory))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetPartDetails_OfConsumption_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PORtConsumptionHead))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mStatu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(POR_SP_GetPartDetails_OfConsumption_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ComplexObject : StructuralObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result : ComplexObject {
        
        private string objectNameField;
        
        private System.Nullable<long> referenceIDField;
        
        private long conH_IDField;
        
        private string siteNameField;
        
        private System.Nullable<long> siteIDField;
        
        private System.Nullable<System.DateTime> consumptionDateField;
        
        private System.Nullable<long> consumedByUserIDField;
        
        private string consumedByUserNameField;
        
        private string engineSerialField;
        
        private string engineModelField;
        
        private string containerField;
        
        private string failureHoursField;
        
        private string failureCauseField;
        
        private string failureNatureField;
        
        private string remarkField;
        
        private string imgConsumptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ConH_ID {
            get {
                return this.conH_IDField;
            }
            set {
                this.conH_IDField = value;
                this.RaisePropertyChanged("ConH_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
                this.RaisePropertyChanged("SiteName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
                this.RaisePropertyChanged("SiteID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> ConsumptionDate {
            get {
                return this.consumptionDateField;
            }
            set {
                this.consumptionDateField = value;
                this.RaisePropertyChanged("ConsumptionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> ConsumedByUserID {
            get {
                return this.consumedByUserIDField;
            }
            set {
                this.consumedByUserIDField = value;
                this.RaisePropertyChanged("ConsumedByUserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ConsumedByUserName {
            get {
                return this.consumedByUserNameField;
            }
            set {
                this.consumedByUserNameField = value;
                this.RaisePropertyChanged("ConsumedByUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EngineSerial {
            get {
                return this.engineSerialField;
            }
            set {
                this.engineSerialField = value;
                this.RaisePropertyChanged("EngineSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EngineModel {
            get {
                return this.engineModelField;
            }
            set {
                this.engineModelField = value;
                this.RaisePropertyChanged("EngineModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Container {
            get {
                return this.containerField;
            }
            set {
                this.containerField = value;
                this.RaisePropertyChanged("Container");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FailureHours {
            get {
                return this.failureHoursField;
            }
            set {
                this.failureHoursField = value;
                this.RaisePropertyChanged("FailureHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FailureCause {
            get {
                return this.failureCauseField;
            }
            set {
                this.failureCauseField = value;
                this.RaisePropertyChanged("FailureCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FailureNature {
            get {
                return this.failureNatureField;
            }
            set {
                this.failureNatureField = value;
                this.RaisePropertyChanged("FailureNature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ImgConsumption {
            get {
                return this.imgConsumptionField;
            }
            set {
                this.imgConsumptionField = value;
                this.RaisePropertyChanged("ImgConsumption");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class POR_SP_GetPartDetails_OfConsumption_Result : ComplexObject {
        
        private long prod_IDField;
        
        private string prod_CodeField;
        
        private string prod_NameField;
        
        private string prod_DescriptionField;
        
        private string uOMField;
        
        private long uOMIDField;
        
        private System.Nullable<decimal> consumedQtyField;
        
        private System.Nullable<long> sequenceField;
        
        private System.Nullable<decimal> currentStockField;
        
        private string gRND_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Prod_ID {
            get {
                return this.prod_IDField;
            }
            set {
                this.prod_IDField = value;
                this.RaisePropertyChanged("Prod_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Prod_Code {
            get {
                return this.prod_CodeField;
            }
            set {
                this.prod_CodeField = value;
                this.RaisePropertyChanged("Prod_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Prod_Name {
            get {
                return this.prod_NameField;
            }
            set {
                this.prod_NameField = value;
                this.RaisePropertyChanged("Prod_Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Prod_Description {
            get {
                return this.prod_DescriptionField;
            }
            set {
                this.prod_DescriptionField = value;
                this.RaisePropertyChanged("Prod_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long UOMID {
            get {
                return this.uOMIDField;
            }
            set {
                this.uOMIDField = value;
                this.RaisePropertyChanged("UOMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> ConsumedQty {
            get {
                return this.consumedQtyField;
            }
            set {
                this.consumedQtyField = value;
                this.RaisePropertyChanged("ConsumedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> CurrentStock {
            get {
                return this.currentStockField;
            }
            set {
                this.currentStockField = value;
                this.RaisePropertyChanged("CurrentStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string GRND_ID {
            get {
                return this.gRND_IDField;
            }
            set {
                this.gRND_IDField = value;
                this.RaisePropertyChanged("GRND_ID");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PORtConsumptionHead))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mStatu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mStatu : EntityObject {
        
        private long idField;
        
        private string objectNameField;
        
        private System.Nullable<long> sequenceField;
        
        private string statusField;
        
        private string remarkField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private long companyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iPartConsumptionChannel : PowerOnRentwebapp.PORServicePartConsumption.iPartConsumption, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iPartConsumptionClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.PORServicePartConsumption.iPartConsumption>, PowerOnRentwebapp.PORServicePartConsumption.iPartConsumption {
        
        public iPartConsumptionClient() {
        }
        
        public iPartConsumptionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iPartConsumptionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPartConsumptionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPartConsumptionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.PORtConsumptionHead GetConsumptionHeadByConsumptionID(long ConsumptionID, string[] conn) {
            return base.Channel.GetConsumptionHeadByConsumptionID(ConsumptionID, conn);
        }
        
        public long SetIntoPartConsumptionHead(PowerOnRentwebapp.PORServicePartConsumption.PORtConsumptionHead ConsumptionHead, string[] conn) {
            return base.Channel.SetIntoPartConsumptionHead(ConsumptionHead, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.mStatu[] GetStatusListForConsumption(string Remark, string state, long UserID, string[] conn) {
            return base.Channel.GetStatusListForConsumption(Remark, state, UserID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] GetConsumptionPartDetailByReceiptID(long ReceiptID, long siteID, string sessionID, string userID, string CurrentObject, string[] conn) {
            return base.Channel.GetConsumptionPartDetailByReceiptID(ReceiptID, siteID, sessionID, userID, CurrentObject, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] GetConsumptionPartDetailByConsumptionID(long ConsumptionID, long siteID, string sessionID, string userID, string CurrentObject, string[] conn) {
            return base.Channel.GetConsumptionPartDetailByConsumptionID(ConsumptionID, siteID, sessionID, userID, CurrentObject, conn);
        }
        
        public void ClearTempDataFromDB(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn) {
            base.Channel.ClearTempDataFromDB(paraSessionID, paraUserID, paraCurrentObjectName, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] GetExistingTempDataBySessionIDObjectName(string paraSessionID, string paraUserID, string paraCurrentObjectName, string[] conn) {
            return base.Channel.GetExistingTempDataBySessionIDObjectName(paraSessionID, paraUserID, paraCurrentObjectName, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] AddPartIntoConsumption_TempDataByPartIDs(string paraProductIDs, string paraSessionID, string paraUserID, string paraCurrentObjectName, long SiteID, string[] conn) {
            return base.Channel.AddPartIntoConsumption_TempDataByPartIDs(paraProductIDs, paraSessionID, paraUserID, paraCurrentObjectName, SiteID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] AddPartIntoConsumption_TempDataByGrdIDs(string GrdIDs, string paraSessionID, string paraUserID, string paraCurrentObjectName, long SiteID, string[] conn) {
            return base.Channel.AddPartIntoConsumption_TempDataByGrdIDs(GrdIDs, paraSessionID, paraUserID, paraCurrentObjectName, SiteID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result[] RemovePartFrom_TempData(string paraSessionID, string paraUserID, string paraCurrentObjectName, int paraSequence, string[] conn) {
            return base.Channel.RemovePartFrom_TempData(paraSessionID, paraUserID, paraCurrentObjectName, paraSequence, conn);
        }
        
        public void UpdatePartConsumedQty_TempData(string SessionID, string CurrentObjectName, string UserID, PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetPartDetails_OfConsumption_Result Consumption, string[] conn) {
            base.Channel.UpdatePartConsumedQty_TempData(SessionID, CurrentObjectName, UserID, Consumption, conn);
        }
        
        public void FinalSavePartDetail(string paraSessionID, string paraCurrentObjectName, long paraReferenceID, string paraUserID, string[] conn) {
            base.Channel.FinalSavePartDetail(paraSessionID, paraCurrentObjectName, paraReferenceID, paraUserID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayByUserID(long UserID, string[] conn) {
            return base.Channel.GetConsumptionSummayByUserID(UserID, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayBySiteIDs(string SiteIDs, string[] conn) {
            return base.Channel.GetConsumptionSummayBySiteIDs(SiteIDs, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayByReceiptIDs(string ReceiptIDs, string[] conn) {
            return base.Channel.GetConsumptionSummayByReceiptIDs(ReceiptIDs, conn);
        }
        
        public PowerOnRentwebapp.PORServicePartConsumption.POR_SP_GetConsumptionSummaryBySiteIDsOrUserIDOrReceiptIDsOrConsumptionIDs_Result[] GetConsumptionSummayByConsumptionIDs(string ConsumptionIDs, string[] conn) {
            return base.Channel.GetConsumptionSummayByConsumptionIDs(ConsumptionIDs, conn);
        }
    }
}
