//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.DocumentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentService.iUC_AttachDocument")]
    public interface iUC_AttachDocument {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/GetDocumentByReferenceId", ReplyAction="http://tempuri.org/iUC_AttachDocument/GetDocumentByReferenceIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] GetDocumentByReferenceId(string BaseObjectName, string TargetObjectName, long ReferenceID, string LoginID, string paraSessionID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/ClearTempData", ReplyAction="http://tempuri.org/iUC_AttachDocument/ClearTempDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        void ClearTempData(string paraSessionID, string paraUserID, string paraObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/FinalSaveToDBtDocument", ReplyAction="http://tempuri.org/iUC_AttachDocument/FinalSaveToDBtDocumentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        void FinalSaveToDBtDocument(string SessionID, long ReferenceID, string UserID, string TargetObjectName, string HttpAppPath, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/InsertIntoTemp", ReplyAction="http://tempuri.org/iUC_AttachDocument/InsertIntoTempResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] InsertIntoTemp(PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result newDocument, string SessionID, string UserID, string TargetObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/CheckDuplicateDocumentTitle", ReplyAction="http://tempuri.org/iUC_AttachDocument/CheckDuplicateDocumentTitleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        string CheckDuplicateDocumentTitle(string paraSessionID, string DocumentTitle, string paraUserID, string currentFormID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/DeleteDocumentFormTemp", ReplyAction="http://tempuri.org/iUC_AttachDocument/DeleteDocumentFormTempResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] DeleteDocumentFormTemp(long DeletedSeq, string paraSessionID, string paraUserID, string paraTargetObjectName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iUC_AttachDocument/GetExistingTempDataBySessionIDObjectNameToR" +
            "ebind", ReplyAction="http://tempuri.org/iUC_AttachDocument/GetExistingTempDataBySessionIDObjectNameToR" +
            "ebindResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] GetExistingTempDataBySessionIDObjectNameToRebind(string paraSessionID, string paraUserID, string paraObjectName, string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_GetDocumentList_Result : ComplexObject {
        
        private System.Nullable<int> idField;
        
        private string objectNameField;
        
        private System.Nullable<long> referenceIDField;
        
        private string documentNameField;
        
        private System.Nullable<long> sequenceField;
        
        private string descriptionField;
        
        private string documentDownloadPathField;
        
        private string documentSavePathField;
        
        private string fileTypeField;
        
        private string keywordsField;
        
        private string accessToField;
        
        private string viewAccessField;
        
        private string dowloadAccessField;
        
        private string deleteAccessField;
        
        private string viewAccess_ValueField;
        
        private string dowloadAccess_ValueField;
        
        private string deleteAccess_ValueField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private System.Nullable<long> customerHeadIDField;
        
        private System.Nullable<long> companyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName {
            get {
                return this.objectNameField;
            }
            set {
                this.objectNameField = value;
                this.RaisePropertyChanged("ObjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentName {
            get {
                return this.documentNameField;
            }
            set {
                this.documentNameField = value;
                this.RaisePropertyChanged("DocumentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DocumentDownloadPath {
            get {
                return this.documentDownloadPathField;
            }
            set {
                this.documentDownloadPathField = value;
                this.RaisePropertyChanged("DocumentDownloadPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DocumentSavePath {
            get {
                return this.documentSavePathField;
            }
            set {
                this.documentSavePathField = value;
                this.RaisePropertyChanged("DocumentSavePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
                this.RaisePropertyChanged("Keywords");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AccessTo {
            get {
                return this.accessToField;
            }
            set {
                this.accessToField = value;
                this.RaisePropertyChanged("AccessTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ViewAccess {
            get {
                return this.viewAccessField;
            }
            set {
                this.viewAccessField = value;
                this.RaisePropertyChanged("ViewAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DowloadAccess {
            get {
                return this.dowloadAccessField;
            }
            set {
                this.dowloadAccessField = value;
                this.RaisePropertyChanged("DowloadAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DeleteAccess {
            get {
                return this.deleteAccessField;
            }
            set {
                this.deleteAccessField = value;
                this.RaisePropertyChanged("DeleteAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ViewAccess_Value {
            get {
                return this.viewAccess_ValueField;
            }
            set {
                this.viewAccess_ValueField = value;
                this.RaisePropertyChanged("ViewAccess_Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DowloadAccess_Value {
            get {
                return this.dowloadAccess_ValueField;
            }
            set {
                this.dowloadAccess_ValueField = value;
                this.RaisePropertyChanged("DowloadAccess_Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DeleteAccess_Value {
            get {
                return this.deleteAccess_ValueField;
            }
            set {
                this.deleteAccess_ValueField = value;
                this.RaisePropertyChanged("DeleteAccess_Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<long> CustomerHeadID {
            get {
                return this.customerHeadIDField;
            }
            set {
                this.customerHeadIDField = value;
                this.RaisePropertyChanged("CustomerHeadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<long> CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SP_GetDocumentList_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class ComplexObject : StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComplexObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SP_GetDocumentList_Result))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iUC_AttachDocumentChannel : PowerOnRentwebapp.DocumentService.iUC_AttachDocument, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iUC_AttachDocumentClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.DocumentService.iUC_AttachDocument>, PowerOnRentwebapp.DocumentService.iUC_AttachDocument {
        
        public iUC_AttachDocumentClient() {
        }
        
        public iUC_AttachDocumentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iUC_AttachDocumentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iUC_AttachDocumentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iUC_AttachDocumentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] GetDocumentByReferenceId(string BaseObjectName, string TargetObjectName, long ReferenceID, string LoginID, string paraSessionID, string[] conn) {
            return base.Channel.GetDocumentByReferenceId(BaseObjectName, TargetObjectName, ReferenceID, LoginID, paraSessionID, conn);
        }
        
        public void ClearTempData(string paraSessionID, string paraUserID, string paraObjectName, string[] conn) {
            base.Channel.ClearTempData(paraSessionID, paraUserID, paraObjectName, conn);
        }
        
        public void FinalSaveToDBtDocument(string SessionID, long ReferenceID, string UserID, string TargetObjectName, string HttpAppPath, string[] conn) {
            base.Channel.FinalSaveToDBtDocument(SessionID, ReferenceID, UserID, TargetObjectName, HttpAppPath, conn);
        }
        
        public PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] InsertIntoTemp(PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result newDocument, string SessionID, string UserID, string TargetObjectName, string[] conn) {
            return base.Channel.InsertIntoTemp(newDocument, SessionID, UserID, TargetObjectName, conn);
        }
        
        public string CheckDuplicateDocumentTitle(string paraSessionID, string DocumentTitle, string paraUserID, string currentFormID, string[] conn) {
            return base.Channel.CheckDuplicateDocumentTitle(paraSessionID, DocumentTitle, paraUserID, currentFormID, conn);
        }
        
        public PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] DeleteDocumentFormTemp(long DeletedSeq, string paraSessionID, string paraUserID, string paraTargetObjectName, string[] conn) {
            return base.Channel.DeleteDocumentFormTemp(DeletedSeq, paraSessionID, paraUserID, paraTargetObjectName, conn);
        }
        
        public PowerOnRentwebapp.DocumentService.SP_GetDocumentList_Result[] GetExistingTempDataBySessionIDObjectNameToRebind(string paraSessionID, string paraUserID, string paraObjectName, string[] conn) {
            return base.Channel.GetExistingTempDataBySessionIDObjectNameToRebind(paraSessionID, paraUserID, paraObjectName, conn);
        }
    }
}
