//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerOnRentwebapp.ProductCategoryService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductCategoryService.iProductCategoryMaster")]
    public interface iProductCategoryMaster {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetProductCategoryList", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryList(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/InsertmProductCategory", ReplyAction="http://tempuri.org/iProductCategoryMaster/InsertmProductCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int InsertmProductCategory(PowerOnRentwebapp.ProductCategoryService.mProductCategory prdCategory, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/updatemProductCategory", ReplyAction="http://tempuri.org/iProductCategoryMaster/updatemProductCategoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        int updatemProductCategory(PowerOnRentwebapp.ProductCategoryService.mProductCategory updatePrdCategory, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListByID", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ProductCategoryService.mProductCategory GetProductCategoryListByID(int prdCategoryId, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecord", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateRecord(string prdCategoryName, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecordEdit", ReplyAction="http://tempuri.org/iProductCategoryMaster/checkDuplicateRecordEditResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        string checkDuplicateRecordEdit(string prdCategoryName, int prdCategoryID, string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetPrdCategoryRecordToBindGrid", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetPrdCategoryRecordToBindGridResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        System.Data.DataSet GetPrdCategoryRecordToBindGrid(string[] conn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListForAsset", ReplyAction="http://tempuri.org/iProductCategoryMaster/GetProductCategoryListForAssetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(vGetProductCagetoryList[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        PowerOnRentwebapp.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryListForAsset(string[] conn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class vGetProductCagetoryList : EntityObject {
        
        private long idField;
        
        private string productCategoryField;
        
        private System.Nullable<long> sequenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
                this.RaisePropertyChanged("ProductCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mProductCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vGetProductCagetoryList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mProductCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(vGetProductCagetoryList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class mProductCategory : EntityObject {
        
        private long idField;
        
        private string nameField;
        
        private System.Nullable<long> sequenceField;
        
        private string activeField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastModifiedByField;
        
        private System.Nullable<System.DateTime> lastModifiedDateField;
        
        private long companyIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastModifiedBy {
            get {
                return this.lastModifiedByField;
            }
            set {
                this.lastModifiedByField = value;
                this.RaisePropertyChanged("LastModifiedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
                this.RaisePropertyChanged("CompanyID");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iProductCategoryMasterChannel : PowerOnRentwebapp.ProductCategoryService.iProductCategoryMaster, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iProductCategoryMasterClient : System.ServiceModel.ClientBase<PowerOnRentwebapp.ProductCategoryService.iProductCategoryMaster>, PowerOnRentwebapp.ProductCategoryService.iProductCategoryMaster {
        
        public iProductCategoryMasterClient() {
        }
        
        public iProductCategoryMasterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iProductCategoryMasterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iProductCategoryMasterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iProductCategoryMasterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PowerOnRentwebapp.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryList(string[] conn) {
            return base.Channel.GetProductCategoryList(conn);
        }
        
        public int InsertmProductCategory(PowerOnRentwebapp.ProductCategoryService.mProductCategory prdCategory, string[] conn) {
            return base.Channel.InsertmProductCategory(prdCategory, conn);
        }
        
        public int updatemProductCategory(PowerOnRentwebapp.ProductCategoryService.mProductCategory updatePrdCategory, string[] conn) {
            return base.Channel.updatemProductCategory(updatePrdCategory, conn);
        }
        
        public PowerOnRentwebapp.ProductCategoryService.mProductCategory GetProductCategoryListByID(int prdCategoryId, string[] conn) {
            return base.Channel.GetProductCategoryListByID(prdCategoryId, conn);
        }
        
        public string checkDuplicateRecord(string prdCategoryName, string[] conn) {
            return base.Channel.checkDuplicateRecord(prdCategoryName, conn);
        }
        
        public string checkDuplicateRecordEdit(string prdCategoryName, int prdCategoryID, string[] conn) {
            return base.Channel.checkDuplicateRecordEdit(prdCategoryName, prdCategoryID, conn);
        }
        
        public System.Data.DataSet GetPrdCategoryRecordToBindGrid(string[] conn) {
            return base.Channel.GetPrdCategoryRecordToBindGrid(conn);
        }
        
        public PowerOnRentwebapp.ProductCategoryService.vGetProductCagetoryList[] GetProductCategoryListForAsset(string[] conn) {
            return base.Channel.GetProductCategoryListForAsset(conn);
        }
    }
}
